### ISSUE TITLE
Invalid JUNIT file

### ISSUE THREAD

**Issue by t-b** [byte-physics/igortest#236]
Running the MIES hardware tests with a ITC1600 hardware results in some test errors. But the generated XML file is also invalid, which should never be the case.

[Run_0002.zip](https://github.com/byte-physics/igor-unit-testing-framework/files/8082707/Run_0002.zip)

**Comment by MichaelHuth** [comment]
Diagnosis: Looks like memory corruption in the string that is saved occurs or on disk. Could not reproduce locally. It might be that the source of the memory corruption is not the unit testing framework itself but MIES using a specific hardware setup. 

This issue needs more input and in best case a reproducible setup for further debugging.
We added some tracking of the issue in MIES in https://github.com/AllenInstitute/MIES/pull/1295 to get better statistics when the issue comes up. (And to prevent Bamboo analyzing partial JUNIT xml files)

**Comment by t-b** [comment]
The MIES PR is now merged. I'm unassigning you until we have some more clues about it.

**Comment by t-b** [comment]
Another file which was generated using running the tests locally with ITC1600 from Tim.
In this case the hardware did *not* crash.

[JU_2022_09_01_171633_2022-09-01_18-24-04.zip](https://github.com/byte-physics/igor-unit-testing-framework/files/9477525/JU_2022_09_01_171633_2022-09-01_18-24-04.zip)

Line 6166 in the hex editor following:
```
00018150: 2061 2068 656c 7090 5306 a839 5600 0090  a help.S..9V...
00018160: 5306 a839 5600 0000 0000 0000 0000 0000  S..9V...........
00018170: 0000 0000 0000 00d0 b5eb a639 5600 0000  ...........9V...
00018180: 0000 0000 0000 00a0 b3eb a639 5600 00f8  ...........9V...
00018190: 5306 a839 5600 0000 0000 0000 0000 00b0  S..9V...........
000181a0: 5306 a839 5600 0000 4000 0000 0000 00b0  S..9V...@.......
000181b0: 5306 a839 5600 0000 0000 0000 0000 0020  S..9V.......... 
```

**Comment by MichaelHuth** [comment]
I suggest we add an allocation of memory to e.g. the XOP at init of ~100 MB. Then we run IP in the Vs debugger and add a conditional breakpoint when a store access happens in the allocated memory.

**Comment by t-b** [comment]
Closing for now.
